# Generated by Django 4.1.3 on 2023-01-20 03:14

from django.db import migrations


def agregar_singletons(apps, schema_editor):
    Convocatoria = apps.get_model('administracion', 'Convocatoria')
    Contacto = apps.get_model('administracion', 'Contacto')
    AcercaDe = apps.get_model('administracion', 'AcercaDe')

    convocatoria = Convocatoria()
    convocatoria.activa = True
    convocatoria.save()

    contacto = Contacto()
    contacto.datos = ""
    contacto.save()

    acerca_de = AcercaDe()
    acerca_de.datos = ""
    acerca_de.save()


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(agregar_singletons)
    ]
