# Generated by Django 4.1.3 on 2023-08-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_convocatoria_activa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
    ]
