# Generated by Django 4.0.4 on 2022-06-07 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vinculacion', '0002_alter_categoria_nombre'),
        ('usuarios', '0005_ubicacion_empresa_nombre_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelInvestigador',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Investigador',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('curp', models.TextField()),
                ('nivel', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, to='investigadores.nivelinvestigador')),
                ('ubicacion', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Investigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('contenido', models.TextField()),
                ('autores', models.ManyToManyField(
                    to='investigadores.investigador')),
                ('categorias', models.ManyToManyField(to='vinculacion.categoria')),
            ],
        ),
    ]
