# Generated by Django 4.0.2 on 2022-06-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculacion', '0002_alter_categoria_nombre'),
        ('investigadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigacion',
            name='autores',
            field=models.ManyToManyField(to='investigadores.Investigador'),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='categorias',
            field=models.ManyToManyField(to='vinculacion.Categoria'),
        ),
    ]
