# Generated by Django 4.0.4 on 2022-06-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0002_alter_investigacion_autores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigador',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='investigador',
            name='latitud',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investigador',
            name='longitud',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GrupoInvestigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('integrantes', models.ManyToManyField(
                    to='investigadores.investigador')),
            ],
        ),
    ]
