# Generated by Django 4.0.2 on 2022-06-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0004_alter_investigador_curp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoinvestigacion',
            name='integrantes',
            field=models.ManyToManyField(to='investigadores.Investigador'),
        ),
    ]
