# Generated by Django 4.0.4 on 2022-06-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0004_alter_investigador_curp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigacion',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
