# Generated by Django 4.0.4 on 2022-06-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0005_alter_investigacion_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoinvestigacion',
            name='administradores',
            field=models.ManyToManyField(
                related_name='%(class)s_administradores', to='investigadores.investigador'),
        ),
        migrations.AlterField(
            model_name='grupoinvestigacion',
            name='integrantes',
            field=models.ManyToManyField(
                related_name='%(class)s_integrantes', to='investigadores.investigador'),
        ),
    ]
