# Generated by Django 4.0.2 on 2022-06-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0005_alter_grupoinvestigacion_integrantes'),
        ('investigadores', '0006_grupoinvestigacion_administradores_and_more'),
    ]

    operations = [
    ]
