# Generated by Django 4.0.5 on 2022-06-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0008_alter_grupoinvestigacion_integrantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigador',
            name='aprobado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
