# Generated by Django 4.0.5 on 2022-06-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0009_investigador_aprobado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigador',
            name='aprobado',
        ),
    ]
