# Generated by Django 4.0.5 on 2022-07-13 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigadores', '0011_alter_investigador_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('estado', models.CharField(choices=[('P', 'En proceso'), ('F', 'Finalizada'), (
                    'I', 'Incumplida'), ('R', 'Rechazada'), ('C', 'Cancelada')], max_length=2, verbose_name='Estado')),
                ('usuario_a_vincular', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                 to='investigadores.investigador', verbose_name='Usuario a vincular')),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                 to=settings.AUTH_USER_MODEL, verbose_name='Usuario solicitante')),
            ],
        ),
    ]
