# Generated by Django 4.0.5 on 2022-07-14 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0012_solicitudtrabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigador',
            name='calle',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investigador',
            name='codigo_postal',
            field=models.CharField(default=11111, max_length=5, validators=[django.core.validators.RegexValidator(
                code='cp_invalido', message='El código postal no tiene un formato válido', regex='\\d{5}')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investigador',
            name='colonia',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investigador',
            name='municipio',
            field=models.IntegerField(choices=[(0, 'Apozol'), (1, 'Apulco'), (2, 'Atolinga'), (3, 'Benito Juárez'), (4, 'Calera'), (5, 'Cañitas de Felipe Pescador'), (6, 'Concepción del Oro'), (7, 'Cuauhtémoc'), (8, 'Chalchihuites'), (9, 'Fresnillo'), (10, 'Trinidad García de la Cadena'), (11, 'Genaro Codina'), (12, 'General Enrique Estrada'), (13, 'General Francisco R. Murguía'), (14, 'El Plateado de Joaquín Amaro'), (15, 'General Pánfilo Natera'), (16, 'Guadalupe'), (17, 'Huanusco'), (18, 'Jalpa'), (19, 'Jerez'), (20, 'Jiménez del Teul'), (21, 'Juan Aldama'), (22, 'Juchipila'), (23, 'Loreto'), (24, 'Luis Moya'), (25, 'Mazapil'), (26, 'Melchor Ocampo'), (27, 'Mezquital del Oro'), (
                28, 'Miguel Auza'), (29, 'Momax'), (30, 'Monte Escobedo'), (31, 'Morelos'), (32, 'Moyahua de Estrada'), (33, 'Nochistlán de Mejía'), (34, 'Noria de Ángeles'), (35, 'Ojocaliente'), (36, 'Pánuco'), (37, 'Pinos'), (38, 'Río Grande'), (39, 'Sain Alto'), (40, 'El Salvador'), (41, 'Sombrerete'), (42, 'Susticacán'), (43, 'Tabasco'), (44, 'Tepechitlán'), (45, 'Tepetongo'), (46, 'Teúl de González Ortega'), (47, 'Tlaltenango de Sánchez Román'), (48, 'Valparaíso'), (49, 'Vetagrande'), (50, 'Villa de Cos'), (51, 'Villa García'), (52, 'Villa González Ortega'), (53, 'Villa Hidalgo'), (54, 'Villanueva'), (55, 'Zacatecas'), (56, 'Trancoso'), (57, 'Santa María de la Paz')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investigador',
            name='numero_exterior',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
