# Generated by Django 4.0.5 on 2022-07-27 18:45

from django.db import migrations, models
import investigadores.models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0013_investigador_calle_investigador_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigador',
            name='acerca_de',
            field=models.TextField(
                default='', max_length=500, verbose_name='Acerca de'),
        ),
        migrations.AddField(
            model_name='investigador',
            name='imagen',
            field=models.ImageField(
                default=None, upload_to=investigadores.models.rutaImagenInvestigador, verbose_name='Imagen'),
        ),
    ]
