# Generated by Django 4.0.5 on 2022-07-29 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigadores', '0016_alter_investigador_acerca_de'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudtrabajo',
            name='usuario_a_vincular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='investigadores.investigador', verbose_name='Usuario a vincular'),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajo',
            name='usuario_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL, verbose_name='Usuario solicitante'),
        ),
    ]
