# Generated by Django 4.0.5 on 2022-08-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0017_alter_solicitudtrabajo_usuario_a_vincular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtrabajo',
            name='descripcion',
            field=models.TextField(default='Descripcion',
                                   max_length=5000, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudtrabajo',
            name='estado',
            field=models.CharField(choices=[('E', 'En espera'), ('A', 'Aceptada'), (
                'R', 'Rechazada')], max_length=1, verbose_name='Estado'),
        ),
    ]
