# Generated by Django 4.0.5 on 2022-09-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0018_solicitudtrabajo_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigacion',
            name='titulo',
            field=models.CharField(max_length=500),
        ),
    ]
