# Generated by Django 4.0.5 on 2022-11-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0020_solicitudtrabajo_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtrabajo',
            name='estado_empleador',
            field=models.CharField(choices=[('E', 'En revisión'), ('P', 'En proceso'), ('A', 'Aceptada'), (
                'R', 'Rechazada'), ('F', 'Finalizada')], default='E', max_length=1, verbose_name='Estado del empleador'),
        ),
        migrations.AddField(
            model_name='solicitudtrabajo',
            name='estado_investigador',
            field=models.CharField(choices=[('E', 'En revisión'), ('P', 'En proceso'), ('A', 'Aceptada'), (
                'R', 'Rechazada'), ('F', 'Finalizada')], default='P', max_length=1, verbose_name='Estado del investigador'),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajo',
            name='estado',
            field=models.CharField(choices=[('E', 'En espera'), ('A', 'Aceptada'), (
                'P', 'En proceso'), ('R', 'Rechazada')], max_length=1, verbose_name='Estado'),
        ),
    ]
