# Generated by Django 4.0.5 on 2022-11-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0021_solicitudtrabajo_estado_empleador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtrabajo',
            name='fecha_finalizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajo',
            name='estado',
            field=models.CharField(choices=[('E', 'En espera'), ('A', 'Aceptada'), ('P', 'En proceso'), (
                'R', 'Rechazada'), ('C', 'Cancelada')], max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajo',
            name='estado_empleador',
            field=models.CharField(choices=[('E', 'En revisión'), ('P', 'En proceso'), ('A', 'Aceptada'), (
                'R', 'Rechazada'), ('F', 'Finalizada')], default='P', max_length=1, verbose_name='Estado del empleador'),
        ),
        migrations.AlterField(
            model_name='solicitudtrabajo',
            name='estado_investigador',
            field=models.CharField(choices=[('E', 'En revisión'), ('P', 'En proceso'), ('A', 'Aceptada'), (
                'R', 'Rechazada'), ('F', 'Finalizada')], default='A', max_length=1, verbose_name='Estado del investigador'),
        ),
    ]
