# Generated by Django 4.0.5 on 2022-11-23 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0022_solicitudtrabajo_fecha_finalizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigacionGoogleScholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.investigador')),
            ],
            options={
                'unique_together': {('investigador', 'titulo')},
            },
        ),
    ]
