# Generated by Django 4.0.5 on 2022-11-24 13:56

from django.db import migrations, models
import investigadores.models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0023_investigaciongooglescholar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigador',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaImagenInvestigador, verbose_name='Imagen de perfil'),
        ),
    ]
