# Generated by Django 4.1.3 on 2023-01-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigadores", "0024_alter_investigador_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="investigador",
            name="link_google_scholar",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
