# Generated by Django 4.1.3 on 2023-02-11 04:33

import django.core.validators
from django.db import migrations, models
import investigadores.models
import investigadores.validators


class Migration(migrations.Migration):

    dependencies = [
        ("investigadores", "0025_investigador_link_google_scholar"),
    ]

    operations = [
        migrations.AddField(
            model_name="investigador",
            name="curriculum_vitae",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to=investigadores.models.rutaCVInvestigador,
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"]),
                    investigadores.validators.limiteTamanioArchivo,
                ],
                verbose_name="Curriculum Vitae",
            ),
        ),
        migrations.AlterField(
            model_name="investigador",
            name="link_google_scholar",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="link_google_scholar_invalido",
                        message="Link de Google Scholar inválido",
                        regex="^https://scholar.google.com/citations\\?user=",
                    )
                ],
                verbose_name="Link de su perfil en Google Scholar",
            ),
        ),
    ]
