# Generated by Django 4.1.3 on 2023-02-24 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculacion', '0007_alter_noticia_fecha'),
        ('investigadores', '0026_investigador_curriculum_vitae_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigacion',
            name='autores',
            field=models.ManyToManyField(blank=True, to='investigadores.investigador'),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='vinculacion.categoria'),
        ),
        migrations.AlterField(
            model_name='investigador',
            name='link_google_scholar',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(code='link_google_scholar_invalido', message='Link de Google Scholar inválido. Un link válido tiene la siguiente estructura: https://scholar.google.com/citations?user=', regex='^https://scholar.google.com/citations')], verbose_name='Link de su perfil en Google Scholar'),
        ),
    ]
