# Generated by Django 4.1.3 on 2023-03-02 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0028_alter_investigador_link_google_scholar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigador',
            name='link_google_scholar',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(code='link_google_scholar_invalido', message='Link de Google Scholar inválido. Un link válido tiene la siguiente estructura: https://scholar.google.com/citations?user=', regex='^https://scholar.google.[a-zA-Z.]+/citations')], verbose_name='Link de su perfil en Google Scholar'),
        ),
    ]
