# Generated by Django 4.1.3 on 2023-03-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0029_alter_investigador_link_google_scholar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigador',
            name='acerca_de',
            field=models.TextField(default='', max_length=1000, verbose_name='Semblanza'),
        ),
    ]
