# Generated by Django 4.1.3 on 2023-06-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0030_alter_investigador_acerca_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigador',
            name='apellidos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investigador',
            name='es_sei',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investigador',
            name='es_sni',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investigador',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
