# Generated by Django 4.1.3 on 2023-06-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0031_investigador_apellidos_investigador_es_sei_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigador',
            name='apellidos',
        ),
        migrations.AlterField(
            model_name='investigador',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
