# Generated by Django 4.1.3 on 2023-06-07 16:07

import django.core.validators
from django.db import migrations, models
import investigadores.models
import investigadores.validators


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0032_remove_investigador_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigador',
            name='grado',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCGInvestigador, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limiteTamanioArchivo], verbose_name='Comprobante de grado'),
        ),
    ]
