# Generated by Django 4.1.3 on 2023-07-14 01:41

import django.core.validators
from django.db import migrations, models
import investigadores.models
import investigadores.validators


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0033_investigador_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigador',
            name='constancia',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaConstanciaInvestigador, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limiteTamanioArchivo], verbose_name='Constancia SEI'),
        ),
    ]
