# Generated by Django 4.1.3 on 2023-08-16 19:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import investigadores.models
import investigadores.validators


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0034_investigador_constancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b1', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Obtención del grado académico de Doctorado o Maestría o Especialidad de los programas del SNP o en el extranjero con beca CONACYT.')),
                ('b2', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Obtención del grado académico de Doctorado o Maestría o Especialidad de un programa nacional.')),
                ('b3', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Dirección de Tesis o Artículo de Investigación de alumnos graduados en licenciatura, maestría, doctorado o especialidad médica.')),
                ('b4', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Dirección de tesis de licenciatura de alumnos graduados en la modalidad de artículo científico.')),
                ('b5', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Presentación de ponencias o carteles en eventos científicos, en México o el extranjero.')),
                ('b6', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Estancias de investigación en instituciones académicas o de investigación.')),
                ('b7', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Asignaturas con créditos impartidas en Especialidad, Maestría o Doctorado de programas del SNP.')),
                ('b8', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Participación en proyectos de investigación con financiamiento interno o externo.')),
                ('b9', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Publicación de artículos en revistas de divulgación científica o tecnológica no arbitradas.')),
                ('b10', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Evaluación de trabajos de investigación o proyectos.')),
                ('estatus', models.CharField(choices=[('I', 'En proceso'), ('E', 'En revisión'), ('G', 'Ganador'), ('F', 'Finalizada')], default='I', max_length=1, verbose_name='Estatus de la solicitud')),
                ('anio', models.CharField(blank=True, max_length=5, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.investigador', verbose_name='Investigador')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Artículos científicos en revistas indexadas o arbitradas.')),
                ('a2', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Autoría y coautoría de libros y/o capítulos de libros científicos con arbitraje.')),
                ('a3', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Trámite de solicitud u obtención de patentes.')),
                ('a4', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Trámite de solicitud u obtención de derechos de obtentor.')),
                ('a5', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Desarrollo de software/hardware con Derechos de Autor.')),
                ('a6', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Implementaciones tecnológicas')),
                ('a7', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Artículos o notas científicas publicadas en revistas arbitradas de divulgación científica o tecnológica.')),
                ('a8', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Participación en proyectos de investigación, desarrollo tecnológico e innovación con financiamiento externo obtenido mediante convocatoria.')),
                ('a9', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Editor, compilador o coordinador de libros colectivos.')),
                ('a10', models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf'], investigadores.validators.limite10MbArchivo)], verbose_name='Pertenencia al Sistema Nacional de Investigadores.')),
                ('estatus', models.CharField(choices=[('I', 'En proceso'), ('E', 'En revisión'), ('G', 'Ganador'), ('F', 'Finalizada')], default='I', max_length=1, verbose_name='Estatus de la solicitud')),
                ('anio', models.CharField(blank=True, max_length=5, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.investigador', verbose_name='Investigador')),
            ],
        ),
    ]
