# Generated by Django 4.1.3 on 2023-08-17 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigadores', '0035_categoriab_categoriaa'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisoresCatA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('a2', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('a3', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('a4', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('a5', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('a6', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('a7', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('a8', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('a9', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('a10', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Revisor')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.categoriaa', verbose_name='Solicitud Categoria')),
            ],
        ),
    ]
