# Generated by Django 4.1.3 on 2023-08-21 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigadores', '0036_revisorescata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisoresCatB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b1', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('b2', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('b3', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('b4', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('b5', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('b6', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('b7', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('b8', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('b9', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('b10', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('estatus', models.CharField(choices=[('I', 'En proceso'), ('E', 'En revisión'), ('G', 'Ganador'), ('F', 'Finalizada')], default='E', max_length=1, verbose_name='Estatus de la revisión')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Revisor')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.categoriaa', verbose_name='Solicitud Categoria')),
            ],
        ),
    ]
