# Generated by Django 4.1.3 on 2023-08-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0037_revisorescatb'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisorescata',
            name='estatus',
            field=models.CharField(choices=[('I', 'En proceso'), ('E', 'En revisión'), ('G', 'Ganador'), ('F', 'Finalizada')], default='E', max_length=1, verbose_name='Estatus de la revisión'),
        ),
    ]
