# Generated by Django 4.1.3 on 2023-08-30 16:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0041_alter_revisorescata_a1_alter_revisorescata_a10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisorescata',
            name='a1',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='A1 - Artículos científicos en revistas indexadas o arbitradas.'),
        ),
        migrations.AlterField(
            model_name='revisorescata',
            name='a10',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='A10 - Pertenencia al Sistema Nacional de Investigadores.'),
        ),
        migrations.AlterField(
            model_name='revisorescata',
            name='a2',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='A2 - Autoría y coautoría de libros y/o capítulos de libros científicos con arbitraje.'),
        ),
        migrations.AlterField(
            model_name='revisorescata',
            name='a3',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='A3 - Trámite de solicitud u obtención de patentes.'),
        ),
        migrations.AlterField(
            model_name='revisorescata',
            name='a4',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='A4 - Trámite de solicitud u obtención de derechos de obtentor.'),
        ),
        migrations.AlterField(
            model_name='revisorescata',
            name='a5',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='A5 - Desarrollo de software/hardware con Derechos de Autor.'),
        ),
        migrations.AlterField(
            model_name='revisorescata',
            name='a6',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='A6 - Implementaciones tecnológicas'),
        ),
        migrations.AlterField(
            model_name='revisorescata',
            name='a7',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='A7 - Artículos o notas científicas publicadas en revistas arbitradas de divulgación científica o tecnológica.'),
        ),
        migrations.AlterField(
            model_name='revisorescata',
            name='a8',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='A8 - Participación en proyectos de investigación, desarrollo tecnológico e innovación con financiamiento externo obtenido mediante convocatoria.'),
        ),
        migrations.AlterField(
            model_name='revisorescata',
            name='a9',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='A9 - Editor, compilador o coordinador de libros colectivos.'),
        ),
        migrations.AlterField(
            model_name='revisorescatb',
            name='b1',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='B1 - Obtención del grado académico de Doctorado o Maestría o Especialidad de los programas del SNP o en el extranjero con beca CONACYT.'),
        ),
        migrations.AlterField(
            model_name='revisorescatb',
            name='b10',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='B10 - Evaluación de trabajos de investigación o proyectos.'),
        ),
        migrations.AlterField(
            model_name='revisorescatb',
            name='b2',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='B2 - Obtención del grado académico de Doctorado o Maestría o Especialidad de un programa nacional.'),
        ),
        migrations.AlterField(
            model_name='revisorescatb',
            name='b3',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='B3 - Dirección de Tesis o Artículo de Investigación de alumnos graduados en licenciatura, maestría, doctorado o especialidad médica.'),
        ),
        migrations.AlterField(
            model_name='revisorescatb',
            name='b4',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='B4 - Dirección de tesis de licenciatura de alumnos graduados en la modalidad de artículo científico.'),
        ),
        migrations.AlterField(
            model_name='revisorescatb',
            name='b5',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='B5 - Presentación de ponencias o carteles en eventos científicos, en México o el extranjero.'),
        ),
        migrations.AlterField(
            model_name='revisorescatb',
            name='b6',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='B6 - Estancias de investigación en instituciones académicas o de investigación.'),
        ),
        migrations.AlterField(
            model_name='revisorescatb',
            name='b7',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='B7 - Asignaturas con créditos impartidas en Especialidad, Maestría o Doctorado de programas del SNP.'),
        ),
        migrations.AlterField(
            model_name='revisorescatb',
            name='b8',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='B8 - Participación en proyectos de investigación con financiamiento interno o externo.'),
        ),
        migrations.AlterField(
            model_name='revisorescatb',
            name='b9',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='B9 - Publicación de artículos en revistas de divulgación científica o tecnológica no arbitradas.'),
        ),
        migrations.AlterField(
            model_name='revisorescatb',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigadores.categoriab', verbose_name='Solicitud Categoria'),
        ),
    ]
