# Generated by Django 4.1.3 on 2023-09-06 20:22

import django.core.validators
from django.db import migrations, models
import investigadores.models
import investigadores.validators


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0042_alter_revisorescata_a1_alter_revisorescata_a10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaa',
            name='a1',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Artículos científicos en revistas indexadas o arbitradas.'),
        ),
        migrations.AlterField(
            model_name='categoriaa',
            name='a10',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Pertenencia al Sistema Nacional de Investigadores.'),
        ),
        migrations.AlterField(
            model_name='categoriaa',
            name='a2',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Autoría y coautoría de libros y/o capítulos de libros científicos con arbitraje.'),
        ),
        migrations.AlterField(
            model_name='categoriaa',
            name='a3',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Trámite de solicitud u obtención de patentes.'),
        ),
        migrations.AlterField(
            model_name='categoriaa',
            name='a4',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Trámite de solicitud u obtención de derechos de obtentor.'),
        ),
        migrations.AlterField(
            model_name='categoriaa',
            name='a5',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Desarrollo de software/hardware con Derechos de Autor.'),
        ),
        migrations.AlterField(
            model_name='categoriaa',
            name='a6',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Implementaciones tecnológicas'),
        ),
        migrations.AlterField(
            model_name='categoriaa',
            name='a7',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Artículos o notas científicas publicadas en revistas arbitradas de divulgación científica o tecnológica.'),
        ),
        migrations.AlterField(
            model_name='categoriaa',
            name='a8',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Participación en proyectos de investigación, desarrollo tecnológico e innovación con financiamiento externo obtenido mediante convocatoria.'),
        ),
        migrations.AlterField(
            model_name='categoriaa',
            name='a9',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaA, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Editor, compilador o coordinador de libros colectivos.'),
        ),
        migrations.AlterField(
            model_name='categoriab',
            name='b1',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Obtención del grado académico de Doctorado o Maestría o Especialidad de los programas del SNP o en el extranjero con beca CONACYT.'),
        ),
        migrations.AlterField(
            model_name='categoriab',
            name='b10',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Evaluación de trabajos de investigación o proyectos.'),
        ),
        migrations.AlterField(
            model_name='categoriab',
            name='b2',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Obtención del grado académico de Doctorado o Maestría o Especialidad de un programa nacional.'),
        ),
        migrations.AlterField(
            model_name='categoriab',
            name='b3',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Dirección de Tesis o Artículo de Investigación de alumnos graduados en licenciatura, maestría, doctorado o especialidad médica.'),
        ),
        migrations.AlterField(
            model_name='categoriab',
            name='b4',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Dirección de tesis de licenciatura de alumnos graduados en la modalidad de artículo científico.'),
        ),
        migrations.AlterField(
            model_name='categoriab',
            name='b5',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Presentación de ponencias o carteles en eventos científicos, en México o el extranjero.'),
        ),
        migrations.AlterField(
            model_name='categoriab',
            name='b6',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Estancias de investigación en instituciones académicas o de investigación.'),
        ),
        migrations.AlterField(
            model_name='categoriab',
            name='b7',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Asignaturas con créditos impartidas en Especialidad, Maestría o Doctorado de programas del SNP.'),
        ),
        migrations.AlterField(
            model_name='categoriab',
            name='b8',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Participación en proyectos de investigación con financiamiento interno o externo.'),
        ),
        migrations.AlterField(
            model_name='categoriab',
            name='b9',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Publicación de artículos en revistas de divulgación científica o tecnológica no arbitradas.'),
        ),
    ]
