# Generated by Django 4.1.3 on 2023-09-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0044_revisorescata_a10_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisorescata',
            name='a10_comentario',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Retroalimentación de la documentación enviada correspondiente al campo A10'),
        ),
        migrations.AlterField(
            model_name='revisorescata',
            name='a1_comentario',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Retroalimentación de la documentación enviada correspondiente al campo A1'),
        ),
        migrations.AlterField(
            model_name='revisorescata',
            name='a2_comentario',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Retroalimentación de la documentación enviada correspondiente al campo A2'),
        ),
        migrations.AlterField(
            model_name='revisorescata',
            name='a3_comentario',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Retroalimentación de la documentación enviada correspondiente al campo A3'),
        ),
        migrations.AlterField(
            model_name='revisorescata',
            name='a4_comentario',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Retroalimentación de la documentación enviada correspondiente al campo A4'),
        ),
        migrations.AlterField(
            model_name='revisorescata',
            name='a5_comentario',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Retroalimentación de la documentación enviada correspondiente al campo A5'),
        ),
        migrations.AlterField(
            model_name='revisorescata',
            name='a6_comentario',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Retroalimentación de la documentación enviada correspondiente al campo A6'),
        ),
        migrations.AlterField(
            model_name='revisorescata',
            name='a7_comentario',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Retroalimentación de la documentación enviada correspondiente al campo A7'),
        ),
        migrations.AlterField(
            model_name='revisorescata',
            name='a8_comentario',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Retroalimentación de la documentación enviada correspondiente al campo A8'),
        ),
        migrations.AlterField(
            model_name='revisorescata',
            name='a9_comentario',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Retroalimentación de la documentación enviada correspondiente al campo A9'),
        ),
        migrations.AlterField(
            model_name='revisorescatb',
            name='b10_comentario',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Retroalimentación de la documentación enviada correspondiente al campo B10'),
        ),
        migrations.AlterField(
            model_name='revisorescatb',
            name='b1_comentario',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Retroalimentación de la documentación enviada correspondiente al campo B1'),
        ),
        migrations.AlterField(
            model_name='revisorescatb',
            name='b2_comentario',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Retroalimentación de la documentación enviada correspondiente al campo B2'),
        ),
        migrations.AlterField(
            model_name='revisorescatb',
            name='b3_comentario',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Retroalimentación de la documentación enviada correspondiente al campo B3'),
        ),
        migrations.AlterField(
            model_name='revisorescatb',
            name='b4_comentario',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Retroalimentación de la documentación enviada correspondiente al campo B4'),
        ),
        migrations.AlterField(
            model_name='revisorescatb',
            name='b5_comentario',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Retroalimentación de la documentación enviada correspondiente al campo B5'),
        ),
        migrations.AlterField(
            model_name='revisorescatb',
            name='b6_comentario',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Retroalimentación de la documentación enviada correspondiente al campo B6'),
        ),
        migrations.AlterField(
            model_name='revisorescatb',
            name='b7_comentario',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Retroalimentación de la documentación enviada correspondiente al campo B7'),
        ),
        migrations.AlterField(
            model_name='revisorescatb',
            name='b8_comentario',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Retroalimentación de la documentación enviada correspondiente al campo B8'),
        ),
        migrations.AlterField(
            model_name='revisorescatb',
            name='b9_comentario',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Retroalimentación de la documentación enviada correspondiente al campo B9'),
        ),
    ]
