# Generated by Django 4.1.3 on 2023-09-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0046_alter_revisorescata_a10_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigador',
            name='es_prodep',
            field=models.CharField(choices=[('True', 'Si'), ('False', 'No')], default=False, max_length=6, verbose_name='¿Esta adscrito al Programa para el Desarrollo Profecional Docente (PRODEP)?'),
        ),
        migrations.AlterField(
            model_name='investigador',
            name='es_sni',
            field=models.CharField(choices=[('True', 'Si'), ('False', 'No')], default=False, max_length=6, verbose_name='¿Esta adscrito al Sistema Nacional de Investigadores (SNI)?'),
        ),
    ]
