# Generated by Django 4.1.3 on 2023-11-23 14:28

import django.core.validators
from django.db import migrations, models
import investigadores.models
import investigadores.validators


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0048_alter_revisorescata_a1_alter_revisorescata_a10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriab',
            name='b3',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Evaluación de trabajos de investigación o proyectos.'),
        ),
        migrations.AlterField(
            model_name='categoriab',
            name='b5',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Presentación de ponencias o carteles en eventos científicos, en México o el extranjero, de manera presencial o virtual y que en todos los casos sean aceptadas por un comité revisor.'),
        ),
        migrations.AlterField(
            model_name='categoriab',
            name='b8',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Participación en proyectos de investigación con financiamiento interno o externo bajo comprobante fiscal.'),
        ),
        migrations.AlterField(
            model_name='categoriab',
            name='b9',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Publicación de artículos en revistas de divulgación científica o tecnológica arbitradas / participación en eventos de divulgación científica.'),
        ),
    ]
