# Generated by Django 4.1.3 on 2023-11-23 15:42

import django.core.validators
from django.db import migrations, models
import investigadores.models
import investigadores.validators


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0049_alter_categoriab_b3_alter_categoriab_b5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaa',
            name='b10',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Evaluación de trabajos de investigación o proyectos.'),
        ),
        migrations.AddField(
            model_name='categoriaa',
            name='b3',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Evaluación de trabajos de investigación o proyectos.'),
        ),
        migrations.AddField(
            model_name='categoriaa',
            name='b5',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Presentación de ponencias o carteles en eventos científicos, en México o el extranjero, de manera presencial o virtual y que en todos los casos sean aceptadas por un comité revisor.'),
        ),
        migrations.AddField(
            model_name='categoriaa',
            name='b6',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Estancias de investigación en instituciones académicas o de investigación.'),
        ),
        migrations.AddField(
            model_name='categoriaa',
            name='b7',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Asignaturas con créditos impartidas en Especialidad, Maestría o Doctorado de programas del SNP.'),
        ),
        migrations.AddField(
            model_name='categoriaa',
            name='b8',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Participación en proyectos de investigación con financiamiento interno o externo bajo comprobante fiscal.'),
        ),
        migrations.AddField(
            model_name='categoriaa',
            name='b9',
            field=models.FileField(blank=True, default=None, null=True, upload_to=investigadores.models.rutaCategoriaB, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limite10MbArchivo], verbose_name='Publicación de artículos en revistas de divulgación científica o tecnológica arbitradas / participación en eventos de divulgación científica.'),
        ),
    ]
