# Generated by Django 4.0.4 on 2022-06-07 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_empresa_institucioneducativa_investigador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.tipousuario'),
        ),
    ]
