# Generated by Django 4.0.4 on 2022-06-07 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_user_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_empresa',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='nombre_institucion',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Investigador',
        ),
        migrations.AddField(
            model_name='empresa',
            name='ubicacion',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.ubicacion'),
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='ubicacion',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.ubicacion'),
        ),
    ]
