# Generated by Django 4.0.4 on 2022-06-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_ubicacion_empresa_nombre_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='tipo',
            field=models.CharField(max_length=30),
        ),
    ]
