# Generated by Django 4.0.5 on 2022-06-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20220625_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
