# Generated by Django 4.1.3 on 2023-08-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='es_revisor',
            field=models.BooleanField(default=False),
        ),
    ]
