# Generated by Django 4.0.2 on 2022-06-20 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vinculacion', '0002_alter_categoria_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=65, verbose_name='Título')),
                ('contenido', models.TextField(
                    max_length=5000, verbose_name='Contenido')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('imagen', models.ImageField(
                    upload_to='noticias/', verbose_name='Imagen')),
                ('escritor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING,
                 to=settings.AUTH_USER_MODEL, verbose_name='Escritor')),
            ],
        ),
    ]
