# Generated by Django 4.0.5 on 2022-07-09 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinculacion', '0004_areaconocimiento_categoria_area_conocimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='area_conocimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='vinculacion.areaconocimiento', verbose_name='Área de conocimiento'),
            preserve_default=False,
        ),
    ]
