# Generated by Django 4.0.5 on 2022-07-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculacion', '0005_alter_categoria_area_conocimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaconocimiento',
            name='nombre',
            field=models.CharField(max_length=70),
        ),
    ]
