# Generated by Django 4.1 on 2022-08-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculacion', '0006_alter_areaconocimiento_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(auto_now=True, verbose_name='Fecha'),
        ),
    ]
