# Generated by Django 4.0.5 on 2022-06-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones_educativas', '0002_rename_user_institucioneducativa_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucioneducativa',
            name='aprobado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
