# Generated by Django 4.0.5 on 2022-06-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones_educativas', '0003_institucioneducativa_aprobado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucioneducativa',
            name='aprobado',
        ),
    ]
