# Generated by Django 4.0.5 on 2022-07-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculacion', '0005_alter_categoria_area_conocimiento'),
        ('instituciones_educativas', '0004_remove_institucioneducativa_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucioneducativa',
            name='especialidades',
            field=models.ManyToManyField(to='vinculacion.categoria'),
        ),
    ]
