# Generated by Django 4.0.5 on 2022-07-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0012_solicitudtrabajo'),
        ('instituciones_educativas', '0005_institucioneducativa_especialidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucioneducativa',
            name='miembros',
            field=models.ManyToManyField(to='investigadores.investigador'),
        ),
    ]
