# Generated by Django 4.0.5 on 2022-07-24 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigadores', '0013_investigador_calle_investigador_codigo_postal_and_more'),
        ('instituciones_educativas', '0008_alter_institucioneducativa_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion_educativa', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='instituciones_educativas.institucioneducativa')),
                ('investigador', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='investigadores.investigador')),
            ],
        ),
    ]
