# Generated by Django 4.0.5 on 2022-11-24 13:56

from django.db import migrations, models
import instituciones_educativas.models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones_educativas', '0010_institucioneducativa_acerca_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucioneducativa',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=instituciones_educativas.models.rutaImagenInstitucion, verbose_name='Imagen de perfil'),
        ),
    ]
