# Generated by Django 4.0.5 on 2022-07-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_empresa_acerca_de_empresa_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='acerca_de',
            field=models.TextField(
                default='', max_length=1000, verbose_name='Acerca de'),
        ),
    ]
