# Generated by Django 4.0.5 on 2022-11-24 13:56

from django.db import migrations, models
import empresas.models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_alter_empresa_acerca_de'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=empresas.models.rutaImagenEmpresa, verbose_name='Imagen de perfil'),
        ),
    ]
