# Generated by Django 4.1.3 on 2022-12-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinculacion', '0007_alter_noticia_fecha'),
        ('empresas', '0010_alter_empresa_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='especialidades',
            field=models.ManyToManyField(blank=True, to='vinculacion.categoria'),
        ),
    ]
