# Generated by Django 4.1.3 on 2023-10-25 05:00

import django.core.validators
from django.db import migrations, models
import empresas.models
import investigadores.validators


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_alter_empresa_especialidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='comprobante',
            field=models.FileField(blank=True, default=None, null=True, upload_to=empresas.models.rutaComprobanteEmpresa, validators=[django.core.validators.FileExtensionValidator(['pdf']), investigadores.validators.limiteTamanioArchivo], verbose_name='Oficio de comprobación de la empresa'),
        ),
    ]
