# Generated by Django 4.1.3 on 2023-10-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0013_empresa_elementos_empresa_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='elementos',
            field=models.TextField(default='', max_length=1000, verbose_name='Elementos con los que cuneta'),
        ),
    ]
