# Generated by Django 4.1.3 on 2023-10-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0014_alter_empresa_elementos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='elementos',
            field=models.TextField(default='', max_length=1000, verbose_name='Elementos con los que cuenta'),
        ),
    ]
